/*
 *  RasterMapTile.h
 *  GlassCockpit
 *
 *  Created by Hugo Vincent on 22/02/09.
 *  Copyright 2009 Hugo Vincent. All rights reserved.
 *
 */

#ifndef RasterMapTile_h
#define RasterMapTile_h

/** This class reads and parses MGMaps cache sets, generated by the MapTileCacher.perl
 *  script (in Util/), version 1.35 tested. 
 */

namespace OpenGC {

class RasterMapTile
{
public:
	RasterMapTile();
};
	
} // end namespace OpenGC

#endif // RasterMapTile_h