// Autogenerated file, do no edit

class FGData {
	double Barometric_Pressure;	// FlightGear property: FIXME
	double External_Temperature;	// FlightGear property: FIXME
	double Wind_Direction;	// FlightGear property: /environment/wind-from-heading-deg
	double Wind_Speed;	// FlightGear property: /environment/wind-speed-kt
	double Director_Airspeed;	// FlightGear property: /controls/autoflight/speed-select
	double Director_Vertical_Speed;	// FlightGear property: /controls/autoflight/vertical-speed-select
	double Director_Roll;	// FlightGear property: /controls/autoflight/bank-angle-select
	double Director_Altitude;	// FlightGear property: /controls/autoflight/altitude-select
	double Director_Heading;	// FlightGear property: /controls/autoflight/heading-select
	bool Director_Active;	// FlightGear property: /controls/autoflight/autopilot[0]/engage
	double Voltage_Battery;	// FlightGear property: FIXME
	double Voltage_Alternator;	// FlightGear property: /controls/engines/engine[0]/generator
	double Engine_Mixture;	// FlightGear property: /controls/engines/engine[0]/mixture
	double Engine_EGT;	// FlightGear property: /engines/engine/egt-degf
	double Engine_CHT;	// FlightGear property: /engines/engine/cht-degf
	double Engine_RPM;	// FlightGear property: /engines/engine/rpm
	double Vertical_Speed_FPM;	// FlightGear property: /velocities/vertical-speed-fps
	double Ground_Speed_MS;	// FlightGear property: /velocities/FIXME
	double Airspeed_KT;	// FlightGear property: /velocities/airspeed-kt
	double Accel_Body_Down;	// FlightGear property: /accelerations/pilot/z-accel-fps_sec
	double Accel_Body_Right;	// FlightGear property: /accelerations/pilot/y-accel-fps_sec
	double Accel_Body_Fwd;	// FlightGear property: /accelerations/pilot/x-accel-fps_sec
	double Altitude_AGL_Feet;	// FlightGear property: /position/altitude-agl-ft
	double Altitude_MSL_Feet;	// FlightGear property: /position/altitude-ft
	double Longitude;	// FlightGear property: /position/longitude-deg
	double Latitude;	// FlightGear property: /position/latitude-deg
	double Track_Heading;	// FlightGear property: FIXME
	double True_Heading;	// FlightGear property: /orientation/heading-deg
	double Pitch;	// FlightGear property: /orientation/pitch-deg
	double Roll;	// FlightGear property: /orientation/roll-deg

	unsigned int magic;
};
