// Autogenerated file, do no edit

class FGData {
	float Barometric_Pressure;	// FlightGear property: FIXME
	float External_Temperature;	// FlightGear property: FIXME
	float Wind_Direction;	// FlightGear property: /environment/wind-from-heading-deg
	float Wind_Speed;	// FlightGear property: /environment/wind-speed-kt
	float Director_Airspeed;	// FlightGear property: /controls/autoflight/speed-select
	float Director_Vertical_Speed;	// FlightGear property: /controls/autoflight/vertical-speed-select
	float Director_Roll;	// FlightGear property: /controls/autoflight/bank-angle-select
	float Director_Altitude;	// FlightGear property: /controls/autoflight/altitude-select
	float Director_Heading;	// FlightGear property: /controls/autoflight/heading-select
	bool Director_Active;	// FlightGear property: /controls/autoflight/autopilot[0]/engage
	float Voltage_Battery;	// FlightGear property: FIXME
	float Voltage_Alternator;	// FlightGear property: /controls/engines/engine[0]/generator
	float Engine_Mixture;	// FlightGear property: /controls/engines/engine[0]/mixture
	float Engine_EGT;	// FlightGear property: /engines/engine/egt-degf
	float Engine_CHT;	// FlightGear property: /engines/engine/cht-degf
	float Engine_RPM;	// FlightGear property: /engines/engine/rpm
	float Vertical_Speed_FPM;	// FlightGear property: /velocities/vertical-speed-fps
	float Ground_Speed_MS;	// FlightGear property: /velocities/FIXME
	float Airspeed_KT;	// FlightGear property: /velocities/airspeed-kt
	float Accel_Body_Down;	// FlightGear property: /accelerations/pilot/z-accel-fps_sec
	float Accel_Body_Right;	// FlightGear property: /accelerations/pilot/y-accel-fps_sec
	float Accel_Body_Fwd;	// FlightGear property: /accelerations/pilot/x-accel-fps_sec
	float Altitude_AGL_Feet;	// FlightGear property: /position/altitude-agl-ft
	float Altitude_MSL_Feet;	// FlightGear property: /position/altitude-ft
	double Longitude;	// FlightGear property: /position/longitude-deg
	double Latitude;	// FlightGear property: /position/latitude-deg
	float Track_Heading;	// FlightGear property: FIXME
	float True_Heading;	// FlightGear property: /orientation/heading-deg
	float Pitch;	// FlightGear property: /orientation/pitch-deg
	float Roll;	// FlightGear property: /orientation/roll-deg

	unsigned int magic;
};
