# Builds: Libraries and application (top level)
# Project: GlassCockpit
# Author: Hugo Vincent
# Date: 22 March 2006, updated 28 August 2010

import os

# Utility Functions:

#CacheDir('/home/hugo/.sconscache') # Enable build object cache

# Configuration options
conf = {
	"debug": False,
	"compiler": 'g++',
	"inc_path": [
		'#../../Source/Base',
		'#../../Source/Gauges',
		'#../../Source/Navigation',
		'#../../Source/DataSources',
		'#../../Source/Application',
		'/usr/include/freetype2', 
		'/usr/include/FTGL'
	],
	"cflags": '-O2 -Wall -Wformat',
	"linkflags": '-Wl,-O2',
	"libpath": ['#build', '/usr/X11R6/lib'],
	"linklibs": [
		'opengc_base',
		'opengc_nav',
		'opengc_gauges',
		'opengc_datasource',
		'GL', 'ftgl', 'fltk', 'fltk_gl', # Core dependencies
		'plibnet', 'plibul', # Needed for FGDataSource
		'opengc_base' # don't know why this needs to be included twice, but hey
	]
}

# Nothing to actually build here, just recurse into the various source directories
SConscript(['BaseSConscript',
			'GaugesSConscript',
			'NavigationSConscript',
			'DataSourcesSConscript',
			'LinuxSConscript'],
			exports='conf')

