# Builds: Gauges library ('libopengc_gauges')
# Project: OpenGC for Albatross
# Author: Hugo Vincent
# Date: 22 March 2006

# Get the top level configuration options
Import('conf')

# All the source files need to be built (none require special treatment)
source = [
	'AltitudeTape.cpp',
	'AlbatrossAnnunciator.cpp',
	'EngineInstruments.cpp',
	'NavDisplay.cpp',
	'Tachometer.cpp',
	'AltitudeTicker.cpp',
	'GenericBargraph.cpp',
	'FlightDirector.cpp',
	'PFD.cpp',
	'PFDOverlay.cpp',
	'VSI.cpp',
	'ArtificialHorizon.cpp',
	'GenericDial.cpp',
	'SpeedTape.cpp',
	'EngineDial.cpp',
	'HeadingIndicator.cpp',
	'SpeedTicker.cpp'
]

# Build the library
Library('#Build/opengc_gauges', source, CPPPATH=conf["inc_path"],
	CCFLAGS=conf["cflags"], CXX=conf['compiler'])

