# Builds: Main application
# Project: OpenGC for Albatross
# Author: Hugo Vincent
# Date: 22 March 2006

# Get the top level configuration options
Import('conf')

# All the source files need to be built (none require special treatment)
source = [
	'Main.cpp',
	'AppObject.cpp'
]

# Build the application
Program('#Build/OpenGC', source, CPPPATH=conf["inc_path"], CXX=conf['compiler'],
	CCFLAGS=conf["cflags"], LIBS=conf["linklibs"], LIBPATH=conf["libpath"],
	LINKFLAGS=conf["linkflags"])

# Build the utility program navconvert (navigation data -> binary converter)
Program('#Build/navconvert', ['NavConvertMain.cpp',
	'#Source/Navigation/BinaryNavData.o'], CPPPATH=conf["inc_path"], 
	CXX=conf['compiler'], CCFLAGS=conf["cflags"], LINKFLAGS=conf["linkflags"])
 
